apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWrite
  nfs:
    path: /somepath
    server: 172.17.0.2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 10
  glusterFs:
    pdName: "abc123"
    fsType: "ext4"